steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/narratives-crm-backend:$SHORT_SHA', './backend']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/narratives-crm-backend:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'narratives-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/narratives-crm-backend:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'

images:
- gcr.io/$PROJECT_ID/narratives-crm-backend:$SHORT_SHA
