// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Avatar struct {
	AvatarID        string `json:"avatarId"`
	UserID          string `json:"userId"`
	AvatarName      string `json:"avatarName"`
	IconURL         string `json:"iconUrl"`
	IconStoragePath string `json:"iconStoragePath"`
	Bio             string `json:"bio"`
	Link            string `json:"link"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type SignedURLPayload struct {
	SignedURL string `json:"signedUrl"`
	PublicURL string `json:"publicUrl"`
}

type User struct {
	UserID            string  `json:"user_id"`
	FirstName         *string `json:"first_name,omitempty"`
	LastName          *string `json:"last_name,omitempty"`
	FirstNameKatakana *string `json:"first_name_katakana,omitempty"`
	LastNameKatakana  *string `json:"last_name_katakana,omitempty"`
	EmailAddress      *string `json:"email_address,omitempty"`
	Role              *string `json:"role,omitempty"`
	CreatedAt         *string `json:"created_at,omitempty"`
	UpdatedAt         *string `json:"updated_at,omitempty"`
	Wallet            *Wallet `json:"wallet,omitempty"`
}

type Wallet struct {
	ID            string   `json:"id"`
	UserID        *string  `json:"user_id,omitempty"`
	WalletAddress *string  `json:"wallet_address,omitempty"`
	Balance       *float64 `json:"balance,omitempty"`
	CreatedAt     *string  `json:"created_at,omitempty"`
	UpdatedAt     *string  `json:"updated_at,omitempty"`
	User          *User    `json:"user,omitempty"`
}
