// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Avatar struct {
	AvatarID        string `json:"avatarId"`
	UserID          string `json:"userId"`
	AvatarName      string `json:"avatarName"`
	IconURL         string `json:"iconUrl"`
	IconStoragePath string `json:"iconStoragePath"`
	Bio             string `json:"bio"`
	Link            string `json:"link"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type SignedURLPayload struct {
	SignedURL string `json:"signedUrl"`
	PublicURL string `json:"publicUrl"`
}
