name: narratives_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.9
  cryptography: ^2.7.0
  convert: ^3.1.0
  graphql_flutter: ^5.1.0
  google_sign_in: ^6.1.5
  googleapis: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/policy.txt
    - assets/images/