// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZuEVrJs1zlkuCqcnGxVFEgqehciGrIQI',
    appId: '1:221090465383:web:49c7e3b0009547c99576c2',
    messagingSenderId: '221090465383',
    projectId: 'narratives-test-64976',
    authDomain: 'narratives-test-64976.firebaseapp.com',
    storageBucket: 'narratives-test-64976.firebasestorage.app',
    measurementId: 'G-S8WZENK6EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyApHfLJzYTYNu0koTkDXjPVEDUmgm8N8',
    appId: '1:221090465383:android:aab2dbf6978d7ce99576c2',
    messagingSenderId: '221090465383',
    projectId: 'narratives-test-64976',
    storageBucket: 'narratives-test-64976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnK6R0dGIwRA9eNqHsf-hmsaRtV1-wCqI',
    appId: '1:221090465383:ios:dda4fbcbcd19e34a9576c2',
    messagingSenderId: '221090465383',
    projectId: 'narratives-test-64976',
    storageBucket: 'narratives-test-64976.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnK6R0dGIwRA9eNqHsf-hmsaRtV1-wCqI',
    appId: '1:221090465383:ios:dda4fbcbcd19e34a9576c2',
    messagingSenderId: '221090465383',
    projectId: 'narratives-test-64976',
    storageBucket: 'narratives-test-64976.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZuEVrJs1zlkuCqcnGxVFEgqehciGrIQI',
    appId: '1:221090465383:web:5373eb9f1af973579576c2',
    messagingSenderId: '221090465383',
    projectId: 'narratives-test-64976',
    authDomain: 'narratives-test-64976.firebaseapp.com',
    storageBucket: 'narratives-test-64976.firebasestorage.app',
    measurementId: 'G-Y5DSWY1H3Q',
  );

}